{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-job
  labels:
{{ include "Commons.Labels" . | indent 4 }}  
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        spec:
        {{- if .Values.ssm.secrets }}
          volumes:
            - name: {{ .Release.Name }}
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: {{ .Release.Name }}
          serviceAccountName: {{ .Values.ssm.config.serviceAccount }}
        {{- end }}
          containers:
          - name: {{ .Values.cronjob.containers.name }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $secretName := .Release.Name -}}
          {{- if .Values.env }}
            env:
            {{- range $key, $val := .Values.env }}
              - name: {{ $key }}
                value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.ssm.secrets }}
            env:
            {{- range $key, $val := .Values.ssm.secrets }}
              - name: {{ $key | upper  }}
                valueFrom:
                  secretKeyRef:
                    name:  {{ $secretName }}
                    key: {{ $key }}
            {{- end }}
            volumeMounts:
              - name: {{ $secretName }}
                mountPath: "/mnt/secrets-store"
                readOnly: true
          {{- end }}
            args:
            {{- range .Values.cronjob.containers.args }}
            - {{ . | quote }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
      parallelism: {{ .Values.cronjob.parallelism }}
      completions: {{ .Values.cronjob.completions }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy  }}
{{- end }}