{{- if and  ( not .Values.cronjob.enabled) ( .Values.hpa.enabled ) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "Commons.Labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hpa.cpu_max }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hpa.cpu_max }}
    {{- end }}
    {{- if .Values.hpa.memory_max }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.hpa.memory_max }}
    {{- end }}
{{- end }}