{{- if .Values.ssm.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }} # the k8s secret name
      type: Opaque
      data:
      {{- range $key, $val := .Values.ssm.secrets }}
        - objectName: {{ $val }} # reference the corresponding parameter
          key: {{ $key }}
      {{- end }}
  parameters:
    objects: |
      - objectName: {{ .Values.ssm.config.secretManagerName | quote }}  # the AWS secret
        objectType: "secretsmanager"
        jmesPath:
        {{- $secretName := .Release.Name -}}
        {{- range $key, $val := .Values.ssm.secrets }}
              - path: {{ printf "%s-%s" $secretName $key | replace "-" "_" | quote }}
                objectAlias: {{ $val | quote }}
        {{- end }}
{{- end }}


