replicaCount: 1
hpa:
  enabled: false
  minReplicas: 3
  maxReplicas: 9
  memory_max: 80
  cpu_max: 80
rollingUpdate:
  enabled: true
  maxSurge: 1
  maxUnavailable: 0
image:
  repository: 740561009084.dkr.ecr.us-east-1.amazonaws.com/your-ms-name
  tag: development-2023-05-03-22-07-47-b9cd8af25b8e758163993cb70c185f5882461be4
  pullPolicy: IfNotPresent
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  annotations:
    prometheus.io/scrape: 'true'
  ports:
    http:
      protocol: TCP
      port: 80
      targetPort: 3100
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    - /
  pathType: ImplementationSpecific
  portName: http
  hosts:
    - test.elven.works
resources:
  limits:
    cpu: 75m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 144Mi
livenessProbe:
  enabled: false
  path: /health
  port: http
  scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
  path: /health
  port: http
  scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
nodeSelector: {}
tolerations: []
affinity: {}
applicationConfig: {}
env: {}
ssm: {}
cronjob:
  enabled: false
  schedule: '*/10 * * * *'
  restartPolicy: OnFailure
  containers:
    name: 1p-chart
