# This is a basic workflow to help you get started with Actions

name: Discord

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1095705266177192006/14cmAWnucoAjmgtLX6lEbQ0_vzKtm7ru7k8OS09f0fSZVWo4t7DBSFhALTFOLKKGEteU
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Deploy production"
          GITHUB_JOB_STATUS: ${{ job.status }}
