name: Pull Request CI
run-name: Running CI/CD Development ElvenWorks 🚀🚀
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
  CI-CD:
    needs: build
    uses: elvenworks/ReusableWorkflow/.github/workflows/push_development.yml@main
    with:
      run-name: "CI-CD"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      FILE_PATH: ${{ secrets.FILE_PATH }}
